### ISSUE TITLE
Retrieving POST and GET data

### ISSUE THREAD

**Issue by konstantinrachev** [chriso/klein.php#275]
Hi guys,

I am stucked into finding a way to retrieve data from controllers dynamically. However if I request the POST or GET data into my controller nothing good shows up.

Thank in advance. :)

**Comment by konstantinrachev** [comment]
My fault. So, I have written my own type of REST requests routing using Klein. However when my form is submitted the POST, respectively GET data is not received by the desired method and controller.

**Comment by Rican7** [comment]
Hmm, I'm still not sure I'm following you @konstantinrachev.
Would you care to show some example code so I can help you further?
