### ISSUE TITLE
Stop Klein from routing sub-directory

### ISSUE THREAD

**Issue by konstantinrachev** [chriso/klein.php#278]
Hi guys,

Is it possible to stop routing for sub-directory and separately to route inside this dir with Klein?

**Comment by doctorallen** [comment]
Can you give an example?

**Comment by Rican7** [comment]
Not sure what you mean exactly, @konstantinrachev. As @doctorallen mentioned, could you give an example to help shed some clarity on your request?

**Comment by abstractcodify** [comment]
example : http://demo.dev/lab/klein/hello-world

root url :  http://demo.dev/lab/klein
