### ISSUE TITLE
Flash message params?

### ISSUE THREAD

**Issue by Seanmcn** [chriso/klein.php#294]
$service->flash($msg, $type = 'info', $params = array())

What is the use of $params here? I expected adding a paramter would make it available with the flash message, which doesn't seem to be the case. I was trying to do something like :

``$this->klein->service()->flash('Record Updated', 'success', array('heading' => '<h4><i class="icon fa fa-check"></i>Success!</h4>'));``

**Comment by jk3us** [comment]
The `$params` is an array that gets passed (with the message) to [`vsprintf()`](https://php.net/manual/en/function.vsprintf.php).  So, you could do something like

    $service->flash("%d records updated.", 'success', [4]);

and it will flash "4 records updated".

**Comment by Seanmcn** [comment]
Ah, okay thanks for the clarification!
