### ISSUE TITLE
Lazy services with parameters

### ISSUE THREAD

**Issue by dan1elhughes** [chriso/klein.php#297]
I get `Missing argument 1 for {closure}()` when I attempt the following:

```php
$router = new \Klein\Klein();

// Register services
$router->respond(function ($request, $response, $service, $app) {
	$app->register('hello', function($world) {
		return "hello $world";
	});
});

// ... Some time later
$router->get('/', function($request, $response, $service, $app) {
	echo $app->hello('world');
});
```

It seems that the issue is [here](https://github.com/chriso/klein.php/blob/master/src/Klein/App.php#L95), as the closure is called with no parameters. I'm currently not familiar enough with the code base to attempt a fix.

**Comment by nbish11** [comment]
Short answer, it can be done. Long answer, it can't be done as it will most likely break compatibility.

The problem is the closure you registered will always return the same _**instance**_ of `Closure` - like a singleton. You could in fact modify the `register` function in the `App` class to accept arguments, like so:

```php
public function register($name, $closure)
{
    if (isset($this->services[$name])) {
        throw new DuplicateServiceException('A service is already registered under '. $name);
    }

    $this->services[$name] = function () use ($closure) {
        static $instance;
        if (null === $instance) {
            $instance = call_user_func_array($closure, func_get_args());
        }
        return $instance;
    };
} 
```

However, because of this line `static $instance` it will always be called with the same args:

```php
$app = new App;

$app->register('hello', function($world) {
	return "hello $world";
});

echo $app->hello('world');  // returns "hello world"
echo $app->hello('test');  // also returns "hello world"
```
I hope I have explained this clearly enough.

**Comment by dan1elhughes** [comment]
I see - very well explained! Looks like major changes would be required to add it.

For anyone looking with the same problem, I've worked around it by registering each service as returning a function, and then I can do the following:

```php
$app->register('hello', function() { 
        return function($world) { 
                return "hello $world";
        }
}

$hello = $app->hello;
echo $hello('world);
```

While probably less efficient, this seems to do the job. Thanks!

**Comment by nbish11** [comment]
:+1: Nice workaround. I didn't even think about returning a function.
