### ISSUE TITLE
String length in chunked response

### ISSUE THREAD

**Issue by bstoy** [chriso/klein.php#309]
I'm trying to get rid of the string length in every chunked response.

Like in the TestCase (/Klein/Tests/ResponseTest.php), the string length seems to be expected, but i dont need it and i want to have a clean json.

        $this->expectOutputString(
            dechex(strlen($content[0]))."\r\n"
            ."$content[0]\r\n"
            .dechex(strlen($content[1]))."\r\n"
            ."$content[1]\r\n"
            .dechex(strlen($content[2]))."\r\n"
            ."$content[2]\r\n"
        );
Please let me know where and which changes i need to make to get this working :)

**Comment by diagnosiadev** [comment]
it is in this fork: https://github.com/Diagnosia/klein.php
